field: ece2df18-646e-4acd-89d3-82a7dd27ad3c
fieldLayouts:
  0986eb32-5b42-482a-9c30-29d800ad25b8:
    tabs:
      -
        fields:
          6c599a44-f7fd-4d1b-be06-35b5411505de:
            required: '0'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  6c599a44-f7fd-4d1b-be06-35b5411505de:
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: '1'
    settings:
      availableTransforms: '*'
      availableVolumes:
        - '1'
        - '2'
        - '3'
        - '4'
        - '5'
        - '8'
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Standard.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: '1'
