field: df8084b9-7522-4db0-a696-53f6f11640a1
fieldLayouts:
  ec841374-7921-40f2-8e5f-5ed77dbf4753:
    tabs:
      -
        fields:
          1efd8f9e-8201-474d-92c5-282f00053747:
            required: '0'
            sortOrder: '2'
          2184e247-ec62-4039-85df-b2721d82bfcd:
            required: '0'
            sortOrder: '5'
          3ed93460-4d0e-4915-a048-82afb2cc02ee:
            required: '0'
            sortOrder: '4'
          7c8a1a34-dadf-44c7-8090-bfa45094c7ea:
            required: '0'
            sortOrder: '1'
          f44368e8-2074-4143-a71d-32c99c7ea9e1:
            required: '1'
            sortOrder: '3'
        name: Content
        sortOrder: '1'
fields:
  1efd8f9e-8201-474d-92c5-282f00053747:
    contentColumnType: text
    fieldGroup: null
    handle: welcomeHeadline
    instructions: ''
    name: Headline
    searchable: '1'
    settings:
      charLimit: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  2184e247-ec62-4039-85df-b2721d82bfcd:
    contentColumnType: string
    fieldGroup: null
    handle: welcomePhoto
    instructions: ''
    name: Photo
    searchable: '1'
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:ffe6bee7-f3f2-41de-9997-df6c2ada6fbe'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      singleUploadLocationSource: 'volume:ffe6bee7-f3f2-41de-9997-df6c2ada6fbe'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1491fd85-7dd7-4f86-8c03-642e538c00ea'
      targetSiteId: null
      useSingleFolder: ''
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  3ed93460-4d0e-4915-a048-82afb2cc02ee:
    contentColumnType: string
    fieldGroup: null
    handle: learnMoreLink
    instructions: ''
    name: 'Learn More Link'
    searchable: '1'
    settings:
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      source: null
      sources:
        - 'section:a6ad0cda-56ac-4e50-adcd-f970f490e975'
      targetSiteId: null
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  7c8a1a34-dadf-44c7-8090-bfa45094c7ea:
    contentColumnType: text
    fieldGroup: null
    handle: welcomeName
    instructions: 'Will be preceeded with "From [name here]"'
    name: 'From Name'
    searchable: '1'
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f44368e8-2074-4143-a71d-32c99c7ea9e1:
    contentColumnType: text
    fieldGroup: null
    handle: welcomeText
    instructions: ''
    name: 'Welcome Text'
    searchable: '1'
    settings:
      charLimit: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: welcome
name: Welcome
sortOrder: '1'
