handle: generalEvent
hasTickets: false
hasTitleField: true
name: 'General Event'
siteSettings:
  4a8c06e2-f6c2-4e05-b6d8-9ba159a22cac:
    hasUrls: true
    template: general/_event
    uriFormat: 'general/{slug}'
titleFormat: ''
titleLabel: Title
