fieldLayouts:
  69bcd06a-d649-49d8-8e47-1175895b5c28:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 38158424-1094-4cc9-93ee-2a3175aa348c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 87a16a2b-c436-4138-a913-43777f0be518
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a06e1794-ac7f-4232-8518-e2b5f6efec13
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: fb66d493-d645-42c8-98fb-4ce365a3164c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b10257e3-e264-4339-9ecc-f425f49a9aa3
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0b53ea16-35d5-4aef-9b82-e0441fc674c9
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
handle: contact
hasTitleField: '0'
name: Contact
section: e7becf5e-029e-4194-9685-77f654342bbf
sortOrder: '1'
titleFormat: '{section.name|raw}'
