fieldLayouts:
  da68b233-eb8e-412d-a4fa-d9737b041672:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 050e10e5-e506-4904-b55a-8efac89dac16
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8d58412c-2c37-4da6-892e-69ab4d8a413b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 38158424-1094-4cc9-93ee-2a3175aa348c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
handle: employment
hasTitleField: '0'
name: Employment
section: 80478b1d-7778-4390-b27a-cf858d8fa19a
sortOrder: '1'
titleFormat: '{section.name|raw}'
