fieldLayouts:
  377b3cdd-fc16-4d6c-9e70-1750b299686a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 38158424-1094-4cc9-93ee-2a3175aa348c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c71c3cc3-1eb6-4611-a354-7b2c6192344a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c7ec24a5-9a21-4585-9efb-17553b9353dc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: df8084b9-7522-4db0-a696-53f6f11640a1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3bf4a6bc-a0ee-4ff9-ad77-4422fc25aca1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9589a0d0-c4b0-40be-94ac-4f56a7c71cb1
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7cbfa01e-6ba5-48cb-8e6f-ad41e3ae745e
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a90872bd-921c-4fa9-aabb-66969fbedef8
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a4abbcc4-e01f-401c-9489-67538e29db58
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 86f0f419-70f3-4723-8ccd-0af12a34c721
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: homepage
hasTitleField: false
name: Homepage
section: 2fc23d44-f539-4fd2-8ff3-9f8cf30ce202
sortOrder: 1
titleFormat: '{section.name|raw}'
