fieldLayouts:
  8cb1fca9-a7e1-44ed-ac0f-42b202aab68c:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 394c7a2d-4f1c-4564-a883-5bce9e143dd7
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 30f13517-4937-4314-bcd4-2ce2be7e22ac
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b0a0c5f9-dbf0-41ff-b56f-779215f6d54f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
handle: jobs
hasTitleField: '1'
name: Jobs
section: 3fcbcd9f-1b33-4012-8340-9ad93ece5604
sortOrder: '1'
titleFormat: null
