fieldLayouts:
  f2459080-ec24-417b-8e7d-692164237cfc:
    tabs:
      -
        elements:
          -
            instructions: null
            label: null
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 050e10e5-e506-4904-b55a-8efac89dac16
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 8d58412c-2c37-4da6-892e-69ab4d8a413b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 058ef289-5e16-41fc-9745-f0325d7d5011
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
handle: newsEventsLanding
hasTitleField: '0'
name: 'News & Events'
section: 9a093c33-b827-44b9-bf0d-d3ad050ffa14
sortOrder: '1'
titleFormat: '{section.name|raw}'
