fieldLayouts:
  91e847c9-4dd8-4c6e-af32-df6fcf5fad78:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: ece2df18-646e-4acd-89d3-82a7dd27ad3c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 30f13517-4937-4314-bcd4-2ce2be7e22ac
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b0a0c5f9-dbf0-41ff-b56f-779215f6d54f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
      -
        elements:
          -
            fieldUid: 91b91157-9fa9-4deb-9507-3bc6002a6722
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 57c99426-6a5d-4b35-aa93-cddf3d76f404
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Meta
        sortOrder: '2'
handle: notice
hasTitleField: '1'
name: Notice
section: 38081c3d-4b57-4105-b21d-1039fb3cb116
sortOrder: '4'
titleFormat: null
