fieldLayouts:
  e558c6d4-a5f3-4208-8b27-466655b704df:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Name
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 7498311f-f6f0-4aee-830a-0b87c29a349f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 38158424-1094-4cc9-93ee-2a3175aa348c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 413ea63e-c279-46e8-aa77-a53544c2c8c4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ece2df18-646e-4acd-89d3-82a7dd27ad3c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 30f13517-4937-4314-bcd4-2ce2be7e22ac
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b0a0c5f9-dbf0-41ff-b56f-779215f6d54f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
      -
        elements:
          -
            fieldUid: 91b91157-9fa9-4deb-9507-3bc6002a6722
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 57c99426-6a5d-4b35-aa93-cddf3d76f404
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Meta
        sortOrder: '2'
handle: story
hasTitleField: '1'
name: Story
section: 38081c3d-4b57-4105-b21d-1039fb3cb116
sortOrder: '6'
titleFormat: null
