fieldLayouts:
  5d32b336-ba04-4a6b-90eb-b8aed24d65c2:
    tabs:
      -
        fields:
          117948cf-a93e-4c29-a86e-c80d11eed4f5:
            required: '0'
            sortOrder: '3'
          3fb0abc8-4bd1-4e6b-a658-f53c6e9ac6d3:
            required: '0'
            sortOrder: '2'
          41c532c2-6106-4305-b799-189374ca1de0:
            required: '0'
            sortOrder: '4'
          4e31b1c2-0dc3-4774-acc9-22753470909e:
            required: '0'
            sortOrder: '1'
          b64234eb-1c5b-4d09-ae19-a9c73d5b2800:
            required: '0'
            sortOrder: '6'
          dd89ecbd-c933-44c6-a467-5890fa0f7186:
            required: '0'
            sortOrder: '5'
        name: Content
        sortOrder: '1'
handle: assetsArticles
hasUrls: '1'
name: 'Assets - News & Events'
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: assets/articles
sortOrder: '2'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
