fieldLayouts:
  79fd2efa-5503-424a-b7f7-6d077afc5d0e:
    tabs:
      -
        fields:
          069c791d-df1c-4f1c-b0a0-86cd754d41e2:
            required: '0'
            sortOrder: '3'
          3fb0abc8-4bd1-4e6b-a658-f53c6e9ac6d3:
            required: '0'
            sortOrder: '2'
          4e31b1c2-0dc3-4774-acc9-22753470909e:
            required: '0'
            sortOrder: '1'
          d2038e70-2cc7-42c2-9fcb-af5a47898466:
            required: '0'
            sortOrder: '4'
        name: Content
        sortOrder: '1'
handle: assetsGeneral
hasUrls: '1'
name: 'Assets - General'
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: assets/general
sortOrder: '1'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
