handle: downloads
hasUrls: '1'
name: Downloads
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: downloads
sortOrder: '3'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
