fieldLayouts:
  ef186e47-e302-4646-9897-d19e3819d573:
    tabs:
      -
        fields:
          3fb0abc8-4bd1-4e6b-a658-f53c6e9ac6d3:
            required: '0'
            sortOrder: '2'
          41c532c2-6106-4305-b799-189374ca1de0:
            required: '0'
            sortOrder: '4'
          479757ec-089d-4ba5-ae9f-468c2ad31ccb:
            required: '0'
            sortOrder: '5'
          4e31b1c2-0dc3-4774-acc9-22753470909e:
            required: '0'
            sortOrder: '1'
          b64234eb-1c5b-4d09-ae19-a9c73d5b2800:
            required: '0'
            sortOrder: '3'
          d2038e70-2cc7-42c2-9fcb-af5a47898466:
            required: '0'
            sortOrder: '6'
        name: Content
        sortOrder: '1'
handle: imagesStaff
hasUrls: '1'
name: 'Images - Staff Photos'
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: images/staff
sortOrder: '4'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
