handle: imagesUser
hasUrls: '1'
name: 'Images - User Photos'
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: images/user
sortOrder: '8'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
