fieldLayouts:
  69dc7ea1-aecd-44f0-8ed6-aa185cdbf529:
    tabs:
      -
        fields:
          3fb0abc8-4bd1-4e6b-a658-f53c6e9ac6d3:
            required: '0'
            sortOrder: '2'
          4e31b1c2-0dc3-4774-acc9-22753470909e:
            required: '0'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
handle: svgIcons
hasUrls: '1'
name: 'SVG - Icons'
settings:
  bucket: marion-prod
  cfDistributionId: ''
  expires: ''
  keyId: AKIAJA52FVZLVIIJ5HAA
  region: us-east-2
  secret: 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
  subfolder: images/svg/icons
sortOrder: '7'
type: craft\awss3\Volume
url: //s3.us-east-2.amazonaws.com/marion-prod/
