contentColumnType: string
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: aspectRatio
instructions: ''
name: 'Aspect Ratio'
searchable: '1'
settings:
  options:
    -
      default: ''
      label: 3x2
      value: 3x2
    -
      default: '1'
      label: 4x3
      value: 4x3
    -
      default: ''
      label: 2x3
      value: 2x3
    -
      default: ''
      label: 3x4
      value: 3x4
    -
      default: ''
      label: 3x1
      value: 3x1
    -
      default: ''
      label: 1x1
      value: 1x1
    -
      default: ''
      label: 16x9
      value: 16x9
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
