contentColumnType: text
fieldGroup: fb7746ab-3959-4e46-8b24-1b2035b322ec
handle: bio
instructions: ''
name: Bio
searchable: '1'
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
