contentColumnType: text
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: caption
instructions: ''
name: Caption
searchable: '1'
settings:
  charLimit: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
