contentColumnType: string
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: feedAuthorEmail
instructions: ''
name: 'Feed Author Email'
searchable: '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Email
