contentColumnType: text
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: hoursOfOperation
instructions: ''
name: 'Hours of Operation'
searchable: '1'
translationKeyFormat: null
translationMethod: none
type: craft\storehours\Field
