contentColumnType: text
fieldGroup: 770fc847-88dc-471d-918d-d241b9efd400
handle: locationHeadline
instructions: ''
name: 'Location Headline'
searchable: '1'
settings:
  charLimit: ''
  columnType: text
  initialRows: '1'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
