contentColumnType: string
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: logo
instructions: 'SVG only!'
name: Logo
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:46f7a110-e30f-4793-adac-8a9a8117ba52'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Select Logo'
  singleUploadLocationSource: 'volume:46f7a110-e30f-4793-adac-8a9a8117ba52'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
