contentColumnType: string
fieldGroup: a4768851-8074-465e-a263-ab7e7141292b
handle: mainMenu
instructions: ''
name: 'Main Menu'
searchable: '1'
settings:
  contentTable: '{{%matrixcontent_mainmenu}}'
  localizeBlocks: false
  maxBlocks: '6'
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
