contentColumnType: text
fieldGroup: d4c986d6-9200-4dfa-967f-daac942dce8f
handle: optimizedImagesBlockPreview
instructions: ''
name: 'Optimized Images Block Preview'
searchable: '1'
settings:
  variants:
    -
      aspectRatioX: '16'
      aspectRatioY: '9'
      format: jpg
      quality: '60'
      retinaSizes:
        - '1'
        - '2'
      useAspectRatio: '1'
      width: '1690'
    -
      aspectRatioX: '16'
      aspectRatioY: '9'
      format: jpg
      quality: '60'
      retinaSizes:
        - '1'
        - '2'
      useAspectRatio: '1'
      width: '1280'
    -
      aspectRatioX: '16'
      aspectRatioY: '9'
      format: jpg
      quality: '60'
      retinaSizes:
        - '1'
        - '2'
      useAspectRatio: '1'
      width: '980'
    -
      aspectRatioX: '16'
      aspectRatioY: '9'
      format: jpg
      quality: '60'
      retinaSizes:
        - '1'
        - '2'
      useAspectRatio: '1'
      width: '736'
    -
      aspectRatioX: '16'
      aspectRatioY: '9'
      format: jpg
      quality: '60'
      retinaSizes:
        - '1'
        - '2'
        - '3'
      useAspectRatio: '1'
      width: '480'
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
