contentColumnType: string
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: primaryImage
instructions: ''
name: 'Primary Image'
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8323c12e-47c9-4b41-91ec-c64d2ee65508'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:8323c12e-47c9-4b41-91ec-c64d2ee65508'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:8323c12e-47c9-4b41-91ec-c64d2ee65508'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
