contentColumnType: string
fieldGroup: fb7746ab-3959-4e46-8b24-1b2035b322ec
handle: staffPhoto
instructions: ''
name: Photo
searchable: '1'
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:ffe6bee7-f3f2-41de-9997-df6c2ada6fbe'
  defaultUploadLocationSubpath: 'employees/{slug}'
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  singleUploadLocationSource: 'volume:1491fd85-7dd7-4f86-8c03-642e538c00ea'
  singleUploadLocationSubpath: '{slug}'
  source: null
  sources:
    - 'volume:ffe6bee7-f3f2-41de-9997-df6c2ada6fbe'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
