contentColumnType: string
fieldGroup: 1baac923-6a88-450e-b39f-63bd7949f12f
handle: video
instructions: 'YouTube or Vimeo URL''s *ONLY* - Other links may break. Make sure the video is allowed to be embedded.'
name: Video
searchable: '1'
settings:
  customPattern: ''
  customPatternErrorMessage: ''
  customPatternToggle: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: barrelstrength\sproutfields\fields\Url
