contentColumnType: string
fieldGroup: 770fc847-88dc-471d-918d-d241b9efd400
handle: welcome
instructions: ''
name: Welcome
searchable: '1'
settings:
  contentTable: '{{%matrixcontent_welcome}}'
  localizeBlocks: false
  maxBlocks: '1'
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
