currLabel: 'Plugin Store'
customIcon: null
enabled: '0'
handle: plugin-store
icon: plugin
layoutId: '2'
newWindow: '0'
order: '9'
prevLabel: 'Plugin Store'
prevUrl: plugin-store
type: '0'
url: plugin-store
