enableVersioning: '1'
handle: pages
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  4a8c06e2-f6c2-4e05-b6d8-9ba159a22cac:
    enabledByDefault: '1'
    hasUrls: '1'
    template: structure/pages/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: '3'
  uid: 6a2d49cc-a2dc-420e-b2e5-a0242ad16480
type: structure
